### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by mzadworny** [mzadworny/self_taught_programmer#1]
This is the code:

y = int

def divider(x):
  x = x / 2
  x = int(x)
  print(x)

def multiplier(x):
  x = x * 4
  x = int(x)
  print(x)

y = divider(6)
p = multiplier(y)
print(p)

This is the error:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from Chapter4_4 import *
  File "/home/runner/selftaughtprogrammer/Chapter4_4.py", line 14, in <module>
    p = multiplier(y)
  File "/home/runner/selftaughtprogrammer/Chapter4_4.py", line 9, in multiplier
    x = x * 4
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

What am I doing wrong?

**Comment by mzadworny** [comment]
Solution - functions need "Return" such as:

def divider(x):
x = x / 2
x = int(x)
return x 

def multiplier(x):
x = x * 4
x = int(x)
return x
